version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: photobooth-postgres
    environment:
      POSTGRES_DB: photobooth
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Pz0zQhhfiB
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d # เพิ่ม init scripts
    networks:
      - photobooth-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: photobooth-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - photobooth-network

  redis:
    image: redis:7-alpine
    container_name: photobooth-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - photobooth-network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  photobooth-network:
    driver: bridge
